files = ["delay_histogram.vhd",
"trigger_detect.vhd",
"trigger_pkg.vhd",
"trigger_rx.vhd",
"trigger_rx_wb.vhd",
"trigger_tx.vhd",
"trigger_tx_wb.vhd",
"trigger_shared_wb.vhd",
"trx_wbgen2_pkg.vhd",
"ttx_wbgen2_pkg.vhd",
"tts_wbgen2_pkg.vhd",
"trigger_dist_core.vhd",
"pack_unpack_pkg.vhd",
"fd_ts_adder.vhd"];
