---------------------------------------------------------------------------------------
-- Title          : Wishbone slave core for Trigger shared module
---------------------------------------------------------------------------------------
-- File           : tts_wbgen2_pkg.vhd
-- Author         : auto-generated by wbgen2 from trigger_shared_wb.wb
-- Created        : Thu Mar 14 23:42:50 2013
-- Standard       : VHDL'87
---------------------------------------------------------------------------------------
-- THIS FILE WAS GENERATED BY wbgen2 FROM SOURCE FILE trigger_shared_wb.wb
-- DO NOT HAND-EDIT UNLESS IT'S ABSOLUTELY NECESSARY!
---------------------------------------------------------------------------------------

library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;
use work.wbgen2_pkg.all;

package tts_wbgen2_pkg is
  
  
  -- Input registers (user design -> WB slave)
  
  type t_tts_in_registers is record
    idr_fw_id_i                              : std_logic_vector(7 downto 0);
    end record;
  
  constant c_tts_in_registers_init_value: t_tts_in_registers := (
    idr_fw_id_i => (others => '0')
    );
    
    -- Output registers (WB slave -> user design)
    
    type t_tts_out_registers is record
      cr_configured_o                          : std_logic;
      cr_clear_tdb_o                           : std_logic;
      end record;
    
    constant c_tts_out_registers_init_value: t_tts_out_registers := (
      cr_configured_o => '0',
      cr_clear_tdb_o => '0'
      );
    function "or" (left, right: t_tts_in_registers) return t_tts_in_registers;
    function f_x_to_zero (x:std_logic) return std_logic;
    function f_x_to_zero (x:std_logic_vector) return std_logic_vector;
end package;

package body tts_wbgen2_pkg is
function f_x_to_zero (x:std_logic) return std_logic is
begin
if(x = 'X' or x = 'U') then
return '0';
else
return x;
end if; 
end function;
function f_x_to_zero (x:std_logic_vector) return std_logic_vector is
variable tmp: std_logic_vector(x'length-1 downto 0);
begin
for i in 0 to x'length-1 loop
if(x(i) = 'X' or x(i) = 'U') then
tmp(i):= '0';
else
tmp(i):=x(i);
end if; 
end loop; 
return tmp;
end function;
function "or" (left, right: t_tts_in_registers) return t_tts_in_registers is
variable tmp: t_tts_in_registers;
begin
tmp.idr_fw_id_i := f_x_to_zero(left.idr_fw_id_i) or f_x_to_zero(right.idr_fw_id_i);
return tmp;
end function;
end package body;
