/*
  Register definitions for slave core: Trigger RX module

  * File           : ../../software/include/hw/trigger_rx_regs.h
  * Author         : auto-generated by wbgen2 from trigger_rx_wb.wb
  * Created        : Thu Mar 14 23:42:50 2013
  * Standard       : ANSI C

    THIS FILE WAS GENERATED BY wbgen2 FROM SOURCE FILE trigger_rx_wb.wb
    DO NOT HAND-EDIT UNLESS IT'S ABSOLUTELY NECESSARY!

*/

#ifndef __WBGEN2_REGDEFS_TRIGGER_RX_WB_WB
#define __WBGEN2_REGDEFS_TRIGGER_RX_WB_WB

#include <inttypes.h>

#if defined( __GNUC__)
#define PACKED __attribute__ ((packed))
#else
#error "Unsupported compiler?"
#endif

#ifndef __WBGEN2_MACROS_DEFINED__
#define __WBGEN2_MACROS_DEFINED__
#define WBGEN2_GEN_MASK(offset, size) (((1<<(size))-1) << (offset))
#define WBGEN2_GEN_WRITE(value, offset, size) (((value) & ((1<<(size))-1)) << (offset))
#define WBGEN2_GEN_READ(reg, offset, size) (((reg) >> (offset)) & ((1<<(size))-1))
#define WBGEN2_SIGN_EXTEND(value, bits) (((value) & (1<<bits) ? ~((1<<(bits))-1): 0 ) | (value))
#endif


/* definitions for register: Control Register */

/* definitions for field: Enable in reg: Control Register */
#define TRX_CR_ENABLE                         WBGEN2_GEN_MASK(0, 1)

/* definitions for field: Reset counters in reg: Control Register */
#define TRX_CR_RST_CNT                        WBGEN2_GEN_MASK(1, 1)

/* definitions for field: Reset histogram in reg: Control Register */
#define TRX_CR_RST_HIST                       WBGEN2_GEN_MASK(2, 1)

/* definitions for field: Broadcast Trigger ID in reg: Control Register */
#define TRX_CR_ID_MASK                        WBGEN2_GEN_MASK(3, 16)
#define TRX_CR_ID_SHIFT                       3
#define TRX_CR_ID_W(value)                    WBGEN2_GEN_WRITE(value, 3, 16)
#define TRX_CR_ID_R(reg)                      WBGEN2_GEN_READ(reg, 3, 16)

/* definitions for register: Received trigger counter register */

/* definitions for register: Executed trigger counter register */

/* definitions for register: RX Histogram bias */

/* definitions for register: RX Histogram Scale */

/* definitions for register: RX trigger delay (cycles) */

/* definitions for register: RX trigger delay (sub-cycle) */
/* definitions for RAM: Delay Histogram Buffer */
#define TRX_DHB_RAM_BASE 0x00000800 /* base address */                                
#define TRX_DHB_RAM_BYTES 0x00000800 /* size in bytes */                               
#define TRX_DHB_RAM_WORDS 0x00000200 /* size in 32-bit words, 32-bit aligned */        
/* [0x0]: REG Control Register */
#define TRX_REG_CR 0x00000000
/* [0x4]: REG Received trigger counter register */
#define TRX_REG_CNTR_RX 0x00000004
/* [0x8]: REG Executed trigger counter register */
#define TRX_REG_CNTR_EXEC 0x00000008
/* [0xc]: REG RX Histogram bias */
#define TRX_REG_RX_HIST_BIAS 0x0000000c
/* [0x10]: REG RX Histogram Scale */
#define TRX_REG_RX_HIST_SCALE 0x00000010
/* [0x14]: REG RX trigger delay (cycles) */
#define TRX_REG_DELAY_C 0x00000014
/* [0x18]: REG RX trigger delay (sub-cycle) */
#define TRX_REG_DELAY_F 0x00000018
#endif
