/*
  Register definitions for slave core: Trigger TX module

  * File           : ../../software/include/hw/trigger_tx_regs.h
  * Author         : auto-generated by wbgen2 from trigger_tx_wb.wb
  * Created        : Thu Mar 14 23:42:50 2013
  * Standard       : ANSI C

    THIS FILE WAS GENERATED BY wbgen2 FROM SOURCE FILE trigger_tx_wb.wb
    DO NOT HAND-EDIT UNLESS IT'S ABSOLUTELY NECESSARY!

*/

#ifndef __WBGEN2_REGDEFS_TRIGGER_TX_WB_WB
#define __WBGEN2_REGDEFS_TRIGGER_TX_WB_WB

#include <inttypes.h>

#if defined( __GNUC__)
#define PACKED __attribute__ ((packed))
#else
#error "Unsupported compiler?"
#endif

#ifndef __WBGEN2_MACROS_DEFINED__
#define __WBGEN2_MACROS_DEFINED__
#define WBGEN2_GEN_MASK(offset, size) (((1<<(size))-1) << (offset))
#define WBGEN2_GEN_WRITE(value, offset, size) (((value) & ((1<<(size))-1)) << (offset))
#define WBGEN2_GEN_READ(reg, offset, size) (((reg) >> (offset)) & ((1<<(size))-1))
#define WBGEN2_SIGN_EXTEND(value, bits) (((value) & (1<<bits) ? ~((1<<(bits))-1): 0 ) | (value))
#endif


/* definitions for register: Control Register */

/* definitions for field: Enable in reg: Control Register */
#define TTX_CR_ENABLE                         WBGEN2_GEN_MASK(0, 1)

/* definitions for field: Reset counter in reg: Control Register */
#define TTX_CR_RST_CNT                        WBGEN2_GEN_MASK(1, 1)

/* definitions for field: Broadcast Trigger ID in reg: Control Register */
#define TTX_CR_ID_MASK                        WBGEN2_GEN_MASK(2, 16)
#define TTX_CR_ID_SHIFT                       2
#define TTX_CR_ID_W(value)                    WBGEN2_GEN_WRITE(value, 2, 16)
#define TTX_CR_ID_R(reg)                      WBGEN2_GEN_READ(reg, 2, 16)

/* definitions for register: TX trigger counter register */

/* definitions for register: TX trigger adjustment (cycles) */

/* definitions for register: TX trigger adjustment (sub-cycle) */
/* [0x0]: REG Control Register */
#define TTX_REG_CR 0x00000000
/* [0x4]: REG TX trigger counter register */
#define TTX_REG_CNTR 0x00000004
/* [0x8]: REG TX trigger adjustment (cycles) */
#define TTX_REG_ADJ_C 0x00000008
/* [0xc]: REG TX trigger adjustment (sub-cycle) */
#define TTX_REG_ADJ_F 0x0000000c
#endif
